Controllers/ItemController.cs
using OnlineFoodOrderingSystem.Models;

using OnlineFoodOrderingSystem.Models.ViewModel;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace OnlineFoodOrderingSystem.Controllers
{
    public class ItemController : Controller
    {
        // GET: Item
        [Authorize(Roles = "Admin")]
        public ActionResult ManageItem()
        {
            return View();
        }
        public JsonResult GetData()
        {
            using (OnlineFoodDBEntities db = new OnlineFoodDBEntities())
            {
                db.Configuration.LazyLoadingEnabled = false;
                List<ItemViewModel> lstitem = new List<ItemViewModel>();
                var lst = db.tblItems.ToList();
                foreach (var item in lst)
                {
                    lstitem.Add(new ItemViewModel() { ItemId = item.ItemId, Title = item.Title, Price = item.Price, Description = item.Description, SmallImage = item.SmallImage, LargeImage = item.LargeImage, IsAvailable = item.IsAvailable });
                }
                return Json(new { data = lstitem }, JsonRequestBehavior.AllowGet);
            }
        }


        [HttpGet]
        public ActionResult AddOrEdit(int id = 0)
        {
            if (id == 0)
            {
                using (OnlineFoodDBEntities db = new OnlineFoodDBEntities())
                {
                    ViewBag.SubMenus = db.tblSubMenus.ToList();
                    ViewBag.Action = "Create New Item";
                    return View(new ItemViewModel());
                }
            }
            else
            {
                using (OnlineFoodDBEntities db = new OnlineFoodDBEntities())
                {
                    ViewBag.Action = "Edit Item";
                    ViewBag.Menus = db.tblSubMenus.ToList();
                    tblItem item = db.tblItems.Where(i => i.ItemId == id).FirstOrDefault();
                    ItemViewModel itemvm = new ItemViewModel();
                    itemvm.ItemId = item.ItemId;
                    itemvm.SubMenuId =Convert.ToInt32( item.SubMenuId);
                    itemvm.Title = item.Title;
                    itemvm.Price = item.Price;
                    itemvm.Description = item.Description;
                    itemvm.SmallImage = item.SmallImage;
                    itemvm.LargeImage = item.LargeImage;
                    //HttpPostedFileBase fup = Request.Files["SmallImage"];
                    //if(fup!=null)
                    //{
                    //    if(fup.FileName!="")
                    //    {
                    //        fup.SaveAs(Server.MapPath("~/img/dogaccessories" + fup.FileName));
                           
                    //    }
                    //}

                    //HttpPostedFileBase fup1 = Request.Files["LargeImage"];
                    //if (fup1 != null)
                    //{
                    //    if (fup1.FileName != "")
                    //    {
                    //        fup1.SaveAs(Server.MapPath("~/img/dogaccessories" + fup1.FileName));
                    //        itemvm.LargeImage = item.LargeImage;
                    //    }
                    //}


                    
                    itemvm.IsAvailable = "Available";

                    ViewBag.SubMenus = db.tblSubMenus.ToList();

                    return View(itemvm);
                }
            }
        }

        [HttpPost]
     
        public ActionResult AddOrEdit(ItemViewModel ivm)
        {
            using (OnlineFoodDBEntities db = new OnlineFoodDBEntities())
            {
                if (ivm.ItemId == 0)
                {
                    tblItem itm = new tblItem();

                    itm.SubMenuId = Convert.ToInt32(ivm.SubMenuId);
                    itm.Title = ivm.Title;
                    itm.Price = ivm.Price;
                    itm.Description = ivm.Description;
                    HttpPostedFileBase fup = Request.Files["SmallImage"];
                    if (fup != null)
                    {
                        if (fup.FileName != "")
                        {
                            fup.SaveAs(Server.MapPath("~/images/ItemImages/" + fup.FileName));
                            itm.SmallImage = fup.FileName;
                        }
                    }

                    HttpPostedFileBase fup1 = Request.Files["LargeImage"];
                    if (fup1 != null)
                    {
                        if (fup1.FileName != "")
                        {
                            fup1.SaveAs(Server.MapPath("~/images/ItemImages/" + fup1.FileName));
                            itm.LargeImage = fup1.FileName;
                        }
                    }
                    itm.IsAvailable = "Available";
                    db.tblItems.Add(itm);
                    db.SaveChanges();
                    ViewBag.Message = "Updated Successfully";
                }
                else
                {
                    tblItem itm = db.tblItems.Where(i => i.ItemId == ivm.ItemId).FirstOrDefault();
                    itm.SubMenuId = Convert.ToInt32(ivm.SubMenuId);
                    itm.Title = ivm.Title;
                    itm.Price = ivm.Price;
                    itm.Description = ivm.Description;
                    HttpPostedFileBase fup = Request.Files["SmallImage"];
                    if (fup != null)
                    {
                        if (fup.FileName != "")
                        {
                            fup.SaveAs(Server.MapPath("~/images/ItemImages/" + fup.FileName));
                            itm.SmallImage = fup.FileName;
                        }
                    }

                    HttpPostedFileBase fup1 = Request.Files["LargeImage"];
                    if (fup1 != null)
                    {
                        if (fup1.FileName != "")
                        {
                            fup1.SaveAs(Server.MapPath("~/images/ItemImages/" + fup1.FileName));
                            itm.LargeImage = fup1.FileName;
                        }
                    }

                   
                    db.SaveChanges();
                    ViewBag.Message = "Updated Successfully";
                   
                }
                ViewBag.SubMenus = db.tblSubMenus.ToList();
                return View(new ItemViewModel());

            }


        }

        [HttpPost]
      
        public ActionResult Delete(int id)
        {
            using (OnlineFoodDBEntities db = new OnlineFoodDBEntities())
            {
                tblItem sm = db.tblItems.Where(x => x.ItemId == id).FirstOrDefault();
                db.tblItems.Remove(sm);
                db.SaveChanges();
                return Json(new { success = true, message = "Deleted Successfully" }, JsonRequestBehavior.AllowGet);
            }
        }
    }
}

Controllers/SubMenuController.cs
using OnlineFoodOrderingSystem.Models;
using OnlineFoodOrderingSystem.Models.ViewModel;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace OnlineFoodOrderingSystem.Controllers
{
    public class SubMenuController : Controller
    {
        [Authorize(Roles ="Admin")]
        public ActionResult ManageSubMenu()
        {
            return View();
        }
        public JsonResult GetData()
        {
            using (OnlineFoodDBEntities db = new OnlineFoodDBEntities())
            {
                db.Configuration.LazyLoadingEnabled = false;
                List<SubMenuViewModel> lst = new List<SubMenuViewModel>();
                var empList = db.tblSubMenus.Select(x => new { SubMenuId = x.SubMenuId,  SubMenuName = x.SubMenuName }).ToList();
                foreach (var item in empList)
                {
                    lst.Add(new SubMenuViewModel() { SubMenuId = item.SubMenuId, SubMenuName = item.SubMenuName });
                }
                return Json(new { data = lst }, JsonRequestBehavior.AllowGet);
            }
        }


        [HttpGet]
        public ActionResult AddOrEdit(int id = 0)
        {
            if (id == 0)
            {
                using (OnlineFoodDBEntities db = new OnlineFoodDBEntities())
                {
                   
                    return View(new SubMenuViewModel());
                }
            }
            else
            {
                using (OnlineFoodDBEntities db = new OnlineFoodDBEntities())
                {
                    SubMenuViewModel sub = new SubMenuViewModel();
                    var menu = db.tblSubMenus.Where(x => x.SubMenuId == id).FirstOrDefault();
                    sub.SubMenuId = menu.SubMenuId;
                    sub.SubMenuName = menu.SubMenuName;
                    return View(sub);
                }
            }
        }

        [HttpPost]
        public ActionResult AddOrEdit(SubMenuViewModel sm)
        {
            using (OnlineFoodDBEntities db = new OnlineFoodDBEntities())
            {
                if (sm.SubMenuId == 0)
                {
                    tblSubMenu tb = new tblSubMenu();
                    tb.SubMenuName = sm.SubMenuName;
                    db.tblSubMenus.Add(tb);
                    db.SaveChanges();
                    return Json(new { success = true, message = "Saved Successfully" }, JsonRequestBehavior.AllowGet);
                }
                else
                {
                    tblSubMenu tbm = db.tblSubMenus.Where(m => m.SubMenuId == sm.SubMenuId).FirstOrDefault();
                    tbm.SubMenuName = sm.SubMenuName;
                    db.SaveChanges();
                    return Json(new { success = true, message = "Updated Successfully" }, JsonRequestBehavior.AllowGet);
                }
            }


        }

        [HttpPost]
        public ActionResult Delete(int id)
        {
            using (OnlineFoodDBEntities db = new OnlineFoodDBEntities())
            {
                tblSubMenu sm = db.tblSubMenus.Where(x => x.SubMenuId == id).FirstOrDefault();
                db.tblSubMenus.Remove(sm);
                db.SaveChanges();
                return Json(new { success = true, message = "Deleted Successfully" }, JsonRequestBehavior.AllowGet);
            }
        }
    }
}

Views/Shared/_AdminLayout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <title>Lumino - Dashboard</title>
    <link href="~/admin/css/bootstrap.min.css" rel="stylesheet">
    <link href="~/admin/css/font-awesome.min.css" rel="stylesheet">
    <link href="~/admin/css/datepicker3.css" rel="stylesheet">
    <link href="~/admin/css/styles.css" rel="stylesheet">
    <link href="~/Content/jquery-ui.min.css" rel="stylesheet" />

    <!--Custom Font-->
    <link href="https://fonts.googleapis.com/css?family=Montserrat:300,300i,400,400i,500,500i,600,600i,700,700i" rel="stylesheet">
</head>

    
       
   
<body>
    <nav class="navbar navbar-custom navbar-fixed-top" role="navigation">
        <div class="container-fluid">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#sidebar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="#"><span>Online Fashion Store</span> Admin</a>
                <ul class="nav navbar-top-links navbar-right">

                    <li class="dropdown">
                        <a class="dropdown-toggle count-info" data-toggle="dropdown" href="#">
                            <em class="fa fa-user-circle"></em>
                        </a>
                        <ul class="dropdown-menu dropdown-alerts">
                            <li>
                                <a href="@Url.Action("ChangePassword","Account")">
                                    <div>
                                        <em class="fa fa-user-secret"></em>Change Password

                                    </div>
                                </a>
                            </li>
                            <li class="divider"></li>
                            <li>
                                <a href="@Url.Action("Logout","Account")">
                                    <div>
                                        <em class="fa fa-sign-out"></em>Logout

                                    </div>
                                </a>
                            </li>
                            <li class="divider"></li>

                        </ul>
                    </li>
                </ul>
            </div>
        </div><!-- /.container-fluid -->
    </nav>
    <div id="sidebar-collapse" class="col-sm-3 col-lg-2 sidebar">
        <div class="profile-sidebar">
            <div class="profile-userpic">
                <img src="http://placehold.it/50/30a5ff/fff" class="img-responsive" alt="">
            </div>
            <div class="profile-usertitle">
                <div class="profile-usertitle-name">Username</div>
                <div class="profile-usertitle-status"><span class="indicator label-success"></span>Online</div>
            </div>
            <div class="clear"></div>
        </div>
        <div class="divider"></div>

        <ul class="nav menu">
            <li class="active"><a href="@Url.Action("DashBoard","Admin")"><em class="fa fa-dashboard">&nbsp;</em> Dashboard</a></li>
            <li><a href="@Url.Action("ManageSubMenu","SubMenu")"><em class="fa fa-building">&nbsp;</em> Manage Category</a></li>

            <li><a href="@Url.Action("ManageItem","Item")"><em class="fa fa-address-book">&nbsp;</em> Manage Item</a></li>
            <li><a href="@Url.Action("ManageOrder","Order")"><em class="fa fa-book">&nbsp;</em> Manage Order</a></li>
            <li><a href="@Url.Action("ManageUser","AdminUser")"><em class="fa fa-user-circle">&nbsp;</em>Manage User</a></li>
            
            <li><a href="@Url.Action("ChangePassword","Account")"><em class="fa fa-user-secret">&nbsp;</em>Change Password</a></li>
            <li><a href="@Url.Action("Logout","Account")"><em class="fa fa-power-off">&nbsp;</em>Logout</a></li>


        </ul>
    </div><!--/.sidebar-->

    <div class="col-sm-9 col-sm-offset-3 col-lg-10 col-lg-offset-2 main">



        @RenderBody()



        <div class="row">

            <div class="col-sm-12">
                <p class="back-link"><a href="#">Online Fashion Store System</a></p>
            </div>
        </div><!--/.row-->
    </div>	<!--/.main-->

    <script src="~/admin/js/jquery-1.11.1.min.js"></script>
    <script src="~/admin/js/bootstrap.min.js"></script>
    <script src="~/js/jquery.validate.min.js"></script>
    <script src="~/js/jquery.validate.unobtrusive.min.js"></script>
    <script src="~/admin/js/chart.min.js"></script>
    <script src="~/admin/js/chart-data.js"></script>
    <script src="~/admin/js/easypiechart.js"></script>
    <script src="~/admin/js/easypiechart-data.js"></script>
    <script src="~/admin/js/bootstrap-datepicker.js"></script>
    <script src="~/admin/js/custom.js"></script>
    <script src="~/js/jquery-ui-1.12.1.min.js"></script>
    <script src="~/js/notify.min.js"></script>
    <script>
        window.onload = function () {
            var chart1 = document.getElementById("line-chart").getContext("2d");
            window.myLine = new Chart(chart1).Line(lineChartData, {
                responsive: true,
                scaleLineColor: "rgba(0,0,0,.2)",
                scaleGridLineColor: "rgba(0,0,0,.05)",
                scaleFontColor: "#c5c7cc"
            });
        };</script>

    @RenderSection("scripts", required: false)

</body>
</html>